# site settings
title: Cedric Rodriguez
email: cedric.j.rodriguez@protonmail.com
landing-title: Hi, I'm Cedric, researcher AI in healthcare.
description: Here, you can find my projects and articles on machine learning and evolutionary intelligence for healthcare.
baseurl: "" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author: Cedric Rodriguez
street_address:
city: Utrecht
state: Utrecht
zip_code: 
country: The Netherlands
about-text: Together with many researchers around me, I work on evolutionary machine learning techniques where, unlike many other techniques, we can find multiple optimal answers for difficult clinical problems with relatively little data. We use the available computing power for the (time-consuming) exploration of different solutions for clinical issues that require a balance between multiple clinical goals, such as; treating a disease as well as possible while minimizing side effects. We do this by simultaneously exploring, combining and evaluating thousands of potential solutions. We then present only the most potential solutions that all represent a different trade-off between the established clinical goals. We then leave it to the medical experts to use their knowledge of the patient's background to choose the solution that is the most appropriate trade-off between the goals set. In this way, we hope that these machine learning techniques are an addition to clinical decision-making where computing power is used to search among thousands/millions of different solutions and where the intuition of the medical expert is used to make the best decision within the individual patient's context.

# homepage config
tiles-count: 3 # number of tiles on home page
post-tiles: true # whether to show post tiles
projects-tiles: true # whether to show project tiles
home-about: false # whether to show about-text in home page or contact page

# social settings
disqus: 'blacksuan19-me' # comments on blog posts
formspree: https://formspree.io/f/xpzoedna # contact form target
# which social media to show on contact page (name needs to match that of social_urls)
preferred_contact: telegram

# add social media links here and they will show up in the footer
# icon: url
social_urls:
    linkedin: https://www.linkedin.com/in/cedricrodriguez/
    github: https://github.com/cedricjakobrodriguez/
    # kaggle: https://www.kaggle.com/abubakaryagob/
    # telegram: https://t.me/blacksuan19
    # android: https://forum.xda-developers.com/member.php?u=5980272
    # instagram:
    # twitter:
    # facebook:
    # pinterest:

# skills widget
skills:

# page groups settings (groups pages with group = true in nav menu)
group_pages: true
group_name: Significant Projects

# external links to be added to the bottom of the menu
# label for the header
extern_name: External Links
# URLs, format name:url
extern_urls:
  Centrum Wiskunde & Informatica: https://www.cwi.nl/people/cedric-rodriguez/
  LUMC AI Research Meetup: https://lumcaimeetup.github.io/

# build settings
markdown: kramdown
kramdown:
  input: GFM
sass:
  style: compressed

# custom directory to fetch pages from
include: ["_pages"]
collections:
  pages:
    output: true
    permalink: "/:path"

# remove dates and prettify links
permalink: pretty

# jekyll admin settings
jekyll_admin:
  hidden_links:
    - datafiles
